UPDATE Building_Flavors
SET Flavor = 9999
WHERE FlavorType = 'FLAVOR_WONDER';
INSERT INTO UnitPromotions_UnitCombats(PromotionType, UnitCombatType)
VALUES
        ('PROMOTION_YYST', 'UNITCOMBAT_CARRIER'),
	('PROMOTION_YYST', 'UNITCOMBAT_NAVALMELEE'),
	('PROMOTION_YYST', 'UNITCOMBAT_NAVALRANGED'),
        ('PROMOTION_YYST', 'UNITCOMBAT_SUBMARINE'),
        ('PROMOTION_YYST', 'UNITCOMBAT_BOMBER'),
        ('PROMOTION_YYST', 'UNITCOMBAT_FIGHTER'),
	('PROMOTION_YYST', 'UNITCOMBAT_MELEE'),
	('PROMOTION_YYST', 'UNITCOMBAT_GUN'),
	('PROMOTION_YYST', 'UNITCOMBAT_MOUNTED'),
        ('PROMOTION_YYST', 'UNITCOMBAT_ARCHER'),
        ('PROMOTION_YYST', 'UNITCOMBAT_HELICOPTER'),
        ('PROMOTION_YYST', 'UNITCOMBAT_SIEGE'),
        ('PROMOTION_YYST', 'UNITCOMBAT_RECON'),
	('PROMOTION_YYST', 'UNITCOMBAT_ARMOR');
ALTER TABLE UnitPromotions ADD COLUMN 'ReligionOwnership' INTEGER DEFAULT 0;